### ISSUE TITLE
Intallation guides for v9 are linked to v10 documentation

### ISSUE THREAD

**Issue by X-Tender** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#112]
'Installation Guide' and 'Getting started links' to the Doc of V10
https://get.typo3.org/version/9

Should link to v9 Documentation.

**Comment by sypets** [comment]
Installation Guide:
* [x] Change in master : link to v10
* [x] Change in v9 branch: link to v9

I did not find any link to get.typo3.org in [Getting Started Tutorial](https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/). @X-Tender Please add link or fix yourself by editing with "Edit me on GitHub".
