### ISSUE TITLE
Rethink structure of installation guide

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#130]
This example shows a complete installation procedure all on one page: https://websiteforstudents.com/install-typo3-cms-using-composer-on-ubuntu-16-04-18-04-with-apache2-mariadb-and-php-7-2-support/

The difficulty of our guide is there are several approaches (with Composer, without) we don't really want to go into how to install the database server, webserver etc. (because that is already very well documented elsewhere) and there are a trillion possible combinations.

On the other hand - I find this all on one page much more readable. Our structure is kind of confusing. We have several pages where the Composer and non-Composer are both on the same page. So you have, "in this case, you do this, in that case do that" (on one page). That is not well readable. 

I am not sure yet, how to solve this. Some approaches:

* split up Composer and non-Composer. Have main part with Composer and another part (possibly separated by toctree caption in main menu) that is for non-Composer installation. Do not have Compser / non-Composer on one page or even on one chapter. 
* the "Quick installation" should have the installation procedure directly on that page (and not on some subpage)

generally:

* avoid hiding things too far in the menu hierarchy
* if things can easily go on one page and not get confusing, put them on one page (but not if there are if / else conditions)

**Comment by tomwarwick** [comment]
We are confident that each of the issues highlighted above have been addressed in the new release of the Getting Started Guide. https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/tree/documentation-draft

- Composer and "legacy" installation guides have been separated with the composer guide being the prominent one of the two.
- The quick installation guide is now just the "Installation Guide".
