### ISSUE TITLE
add a new section "Migrate TYPO3 to another Server"

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#145]
Information about t3d Export should be moved and updated here:
https://wiki.typo3.org/Faq/copy_parts_of_a_running_TYPO3_system_to_another_server
Alternative strategies discussed...

**Comment by linawolf** [comment]
Some Information to be included:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Feature-72749-CLISupportForT3DImport.html

**Comment by tomwarwick** [comment]
@linawolf does https://docs.typo3.org/m/typo3/guide-installation/11.5/en-us/MigrateContent/Index.html
address this issue?
