### ISSUE TITLE
Add information about "subtree split"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#156]
This is mentioned in chapter about "migrating to Composer" but if you start with Composer you will probably never see this. I think it might be a good idea to document this somewhere (and make it possible to link there from elsewhere).

Problem is, not sure where and if this should go in "Installation Guide" or "TYPO3 Explained".

Also, we should update places which still recommend to install `typo3/cms`

**Comment by susannemoog** [comment]
to `typo3/cms`: yes we should.
however, I would not document the subtree split at this point (at least not in user facing manuals, if necessary, that would imho be core contribution guide) - as it is largely irrelevant to users how the packages are internally generated.
