### ISSUE TITLE
Document Composer: How it works

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#157]
There is some very good explanation in the [TYPO3 Wiki Composer page](https://wiki.typo3.org/Composer) but this has not been updated and some of it is outdated. 

I think it might be a good idea to use Wiki page or start from scratch and document how it works, with a focus on the TYPO3 specific stuff.

Some parts in the Wiki TYPO3 Composer page might be useful for this:

* https://wiki.typo3.org/Composer#TYPO3_Ecosystem_and_Composer_Ecosystem, especially:
  * Composer installer: https://wiki.typo3.org/Composer#TYPO3_Composer_installers

Some of this might be more on-topic in "TYPO3 Explained", e.g.

* Composer and non-Composer mode - what is the difference internally?
* autoloading (we already have this in "TYPO3 Explained").

**Comment by susannemoog** [comment]
As Felicity wanted the original content from the wiki for reference:

Class loader:
```
Integrating Composer class loader into TYPO3 CMS
In our efforts to make the TYPO3 CMS system faster and closer oriented to common PHP standard systems, we looked into the integration of the class loader that is used by all composer-based projects. We consider this functionality a crucial feature for the future of TYPO3 CMS on the base level, but also as a dramatic increase of the overall performance of every request inside TYPO3 CMS.

Understanding the TYPO3 CMS class loader
The TYPO3 class loader is instantiated within the TYPO3 CMS Bootstrap at a very early point. It does a lot of logic (checking ext_autoload.php, ClassAliasMap.php), and caches this logic away on a per-class basis by default in typo3temp/Cache/ to store all information for a class. This information contains: The full path to the class, the namespaced class name itself and possible class aliases.

The latter part looks into all extensions and checks the Migrations/ClassAliasMap.php file for any possible “legacy class” that could be used (e.g. t3lib_extmgm). This way, all extensions still using non-namespaced class that are shipped with the TYPO3 core are still made available.

The information is stored in a SimpleFileBackend via the built-in Caching Framework by default. At the early stage of the bootstrap process some classes need to be included manually as the whole TYPO3 core engine has not been loaded yet. This is done for all PHP classes in use, which may result in 500+ files inside typo3temp/Cache which are created one by one on an initial request with no caches set up. This is done by intention on a per-file-basis during runtime as a cache file is only created if a PHP class is requested to be instantiated. On a second hit, the caching framework does not create the cache files, but fetches one by one for each class used in the request via a separate file_get_contents() call.

When debugging the TYPO3 CMS system on an initial request, there are a lot of file_get_contents() and file_put_contents() calls to store and fetch this information. This is quite a lot of overhead for loading PHP classes. Even without a lot of class aliases (e.g. in CMS7) this overhead of writing / storing the file caches still exists. Some overhead however is already taken care, especially if a class is loaded which is shipped with the core and no class alias is used.

This is all built in a way so a lot of backwards-compatibility can be ensured.

Understanding the Composer class loader
Compared to the TYPO3 CMS class loader, the composer class loader concept differs in the following major points:

Caching on build stage
When setting up a project, like a TYPO3 CMS project, Composer checks the main composer.json of a project and builds a static file with all PSR-4 prefixes defined in that json file. Unless in a development environment or when updating the source, this file does not need to be rebuilt as the PHP classes of the loaded packages won’t change in a regular instance. This way all classes available inside TYPO3 CMS are always available to the class loader.

Using PSR-4 compatible prefix-based resolving
Instead of looking up every single class and caching the information away, composer works on a “prefix”-based resolution. As an example, the Composer class loader only needs to know that all PHP classes starting with TYPO3\CMS\Core are located within typo3/sysext/core/Classes. The rest is done by a simple resolution to include the necessary PHP class files. This means that the information to be cached away is only the list of available namespace-prefixes. All classes inside the TYPO3 CMS Core are PSR-4 compatible since TYPO3 CMS 6.0 already.

The definition of these prefixes is set inside the composer.json of each package or distribution / project. In the TYPO3 CMS Core, every system extension defined these namespace prefixes already since TYPO3 CMS 7.1 and TYPO3 CMS 6.2.10.

Autoloading developer-specific data differently
The composer class loader checks the composer.json for a development installation differently, including e.g. Unit and Functional Tests separately to the rest of the installation. The static map with all namespaces are thus different when using Composer with "composer install" or "composer install --no-dev"

Integration Approach
The Composer class loader is injected inside the Bootstrap process of TYPO3 CMS and registered before the TYPO3 class loader. This means that a lookup on a class name is first checked via the Composer logic, and if none found, the regular TYPO3 class loader takes over.

The support for class aliases is quite important for TYPO3 CMS, but is not supported by Composer by default. There is a separate Composer package created by Helmut Hummel (available on https://github.com/helhum/class-alias-loader) which serves as a facade to the Composer class loader and creates not just the information for the prefixes but also the available class aliases for a class and loads them as well.

The necessary information about the “which namespaced classes can be found at which place” is created before every release and shipped inside the typo3_src directory. The generated class information is available under typo3/contrib/vendor/composer/. For TYPO3 installations that are set up with composer, the TYPO3 bootstrap checks Packages/Libraries/autoload.php first which can be shipped with any composer-based project and include many more PHP Composer packages than just TYPO3 extensions. To ensure maximum backwards-compatibility, the option to load from Packages/Library/autoload.php instead of the shipped "required-core-packages-only" needs to be activated via an environment variable called "TYPO3_COMPOSER_AUTOLOAD" which needs to be set on server-side level.

If the composer-based logic is not used in some legacy cases (for extensions etc), the usual TYPO3 class loader comes into play and does the same logic as before. Please note that during the CMS7 development this might be improved further.

See the following reviews for the change:

https://review.typo3.org/#/c/36091/
https://review.typo3.org/#/c/36076/
https://review.typo3.org/#/c/36644/
Backport Considerations
We backported the base functionality to TYPO3 CMS 6.2. The integration of the Composer class loader decreases the loading of a frontend page inside a real-life installation up to 10% on a “first hit” (no caches set up) and up to 8% on a fully cached page. This leads to fewer race conditions while setting up class loader caches, as the TYPO3 class loader cache is not as populated as much as before. The IO access to the file systems is decreased due to less lookups of classes in temporary files. If used in a pure-composer-setup together with the environment variable "TYPO3_COMPOSER_AUTOLOAD" activated, the performance increase will be even bigger.

The integration is a 1:1 backport without adaptations to the base code, only to load different class maps. The functionality contains proper fallbacks, so there will be no breaking changes.

Do I need a Packages/ directory then for 6.2 as well?
No. For 6.2 a pre-generated autoload.php (and additional necessary files) are committed to “typo3/contrib/vendor” directory and used for the TYPO3 core if it is not installed via composer.

Project Setup and Extension Considerations
If you already use Composer to set up your project, and the composer.json and their extensions ship a valid composer.json, the Composer class loader generates the valid PSR-4 cache file with all prefixes on installation and update. Running "composer update" will automatically re-generate the PSR-4 cache file.

The Composer class loader also supports PSR-0 and static inclusion of files, which can be used as well.

As a base line: Any regular installation will see a proper speed improvement after the update to the Composer class loader.

How to Measure
We used xhprof to profile the overall performance with a default caching setup shipped with the TYPO3 CMS default configuration.

We measured non-cached page (after clearing all caches, including system caches) and a fully cached page. Of course any TYPO3 backend requests profit from this change as well.

We noticed a decrease in request times, and the number of function calls, as well as large drop of file_get_contents() and file_put_contents() in the function calls.

We measured these changes with a 6.2 installation as well as a TYPO3 installation on master, the first one set up with the tarball distribution shipped on typo3.org.```

Composer:
```
TYPO3 Ecosystem and Composer Ecosystem
TYPO3 Extensions
TYPO3 has the concept of extensions since very early versions. The TYPO3 core consists of a couple of selected extensions and there are many third party extensions available in the TYPO3 Extension Repository. TYPO3 extensions' meta data and installation instructions are defined in a ext_emconf.php file. Extensions are identified by the extension key which can consist of alphanumerical characters and underscores. Extensions reside in the typo3conf/ext/ directory in a folder matching the extension key e.g. extension news will reside in the folder typo3conf/ext/news.

Composer Packages
In the Composer Ecosystem everything is (called) a package. The central package repository for Composer packages is Packagist. Composer packages' meta data and installation instructions are defined in a composer.json file. Composer packages have a unique name, which has two parts. It starts with the vendor, followed by a slash, followed by a package name. All packages downloaded by composer are placed in the so called vendor directory e.g. the package symfony/console will reside in the folder vendor/symfony/console

All these differences would normally make it impossible to package TYPO3 and extensions by using composer. To work around these limitations, two things were introduced:

composer.typo3.org composer repository for TER extensions
The TYPO3 composer installers
composer.typo3.org
This is a composer package repository which makes all TER extensions installable via composer, if https://composer.typo3.org is added to the root composer.json as additional composer repository. This is done by regularly checking the contents of the TER (basically all ext_emconf.php info from all extensions in each version is fetched from within the extensions.xml file) and is transformed into a Composer readable package information format.

With that service, extensions can be installed via composer, even if they do not have an own composer.json file.

Since Composer requires packages to have a vendor prefix, all extensions downloadable from composer.typo3.org have the prefix typo3-ter/ followed by the extension key, where the underscores are replaced by a dash. This means that e.g. the extension tt_news is available as typo3-ter/tt-news. The code which does the composer package information from TER extension information is available on Github

TYPO3 Composer installers
A composer.json file was added to the TYPO3 git repository and the repository was registered on Packagist with the name typo3/cms. This means that requiring typo3/cms as composer package would be easy, but setting up everything to have a familiar directory structure (including all symlinks) would be up to every user. Also the TYPO3 core and the extensions would be placed in the vendor directory, where they would be inaccessible for TYPO3.

To tackle these differences in the folder structure and to be able to download and extract *.t3x extension packages, the typo3/cms-composer-installers composer package was created and added to typo3/cms as dependency. So every time you require typo3/cms with composer, the installers are also downloaded.

typo3/cms-composer-installers acts as a composer plugin which handles installation, update and deletion of composer packages of the types typo3-cms-framework and typo3-cms-extension. The first type is used as type for typo3/cms, the latter type for all TYPO3 extensions (on composer.typo3.org).

The installer does four things:

It downloads and extracts extensions (as t3x from the TER) into the typo3conf/ext/ directory
It puts the TYPO3 sources into a specified directory (typo3_src by default)
It establishes symlinks to the typo3 directory and the index.php file
It establishes a symlink from vendor/autoload.php within the TYPO3 sources directory to the real autoload.php of Composer (a wrapper script is created if symlinking is not possible), this allows you to use arbitrary vendor directories
TYPO3 7LTS and later
In general there are two options to use TYPO3 in a project.

Composer Mode
Classic Mode (Non Composer Mode)
Composer Mode means, that the typo3/cms package is installed via the composer command line utility Composer. In order for this to work you need a composer.json file in the root of your project, which describes your project and it's dependencies(TYPO3 sources, Extensions and their versions). As a simple starting point there are example projects(distribution) that you can use to kickstart your project. However eventually you will have to learn and understand the content of the composer.json file in order to have full control over your project. See below for more details on the process of installation.

The TYPO3 Extension manager module must NOT be used to fetch or update extensions in Composer Mode, therefore the download and update functionality is disabled. It is only remains possible to activate extensions and change extension settings.

Classic Mode (Non Composer Mode) means, that the TYPO3 sources are fetched as a tarball and symlinked into (or used as) the document root. Alternatively the sources can be fetched via git, but a composer install is then required before they are ready to be used in a symlinked setup like described above.

Warning - Message
Cloning the typo3 source repository and doing a composer install will eventually lead to an installation in "Classic Mode" as you are adding the dependencies of TYPO3 but the typo3 package itself is NOT a dependency of your project.
Composer Mode
Installation
composer create-project typo3/cms-base-distribution could be used to kickstart your composer.json from an example (distribution). However it is not always updated with the latest TYPO3 version. Therefor we rather recommend to use a custom, minimum distribution composer.json like this:

JavaScript:
{
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" }
  ],
  "name": "my-vendor/my-typo3-cms-distribution",
  "require": {
    "typo3/cms": "^8.0"
  }
}
Doing a composer install will result in the following directory structure:

drwxr-xr-x   vendor
-rw-r--r--   composer.json
-rw-r--r--   composer.lock
lrwxr-xr-x   index.php -> typo3_src/index.php
lrwxr-xr-x   typo3 -> typo3_src/typo3
drwxr-xr-x   typo3_src
For security reasons it is however not recommended to have the vendor directory and the TYPO3 sources directory in the document root.

Because of that it is possible (and highly recommended) to add configuration to put the web root typo3/cms package elsewhere after a composer installation. The configuration must be added to the extra section of the root composer.json like that:

JavaScript:
{
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" }
  ],
  "name": "my-vendor/my-typo3-cms-distribution",
  "require": {
    "typo3/cms": "^8.0"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web"
    }
  }
}
This will result in the following directory structure: (If you change these settings, you need to clean up (e.g. via rm -rf index.php typo3 typo3_src before doing another composer install)

drwxr-xr-x   vendor
drwxr-xr-x   web
-rw-r--r--   composer.json
-rw-r--r--   composer.lock
And the web directory looks like this:

lrwxr-xr-x   index.php -> ../vendor/typo3/cms/index.php
lrwxr-xr-x   typo3 -> ../vendor/typo3/cms/typo3
The typo3/cms package resides in the vendor folder, which will be the default configuration option soon. The web folder for now still has symlinks to the typo3 folder and the typo3conf folder will also be present there after setting up TYPO3. But at least the vendor directory and the composer.json and composer.lock files are outside the document root, which already is an improvement.

Class Loading
In Composer Mode all class loading information must be provided by each of the installed extensions or the root package. If TYPO3 extensions are not installed by composer, e.g. because they are directly committed to the root package or a new package is kickstarted, class loading information needs to be provided, otherwise no classes can be loaded for these extensions/ packages.

E.g. if you have a site extension directly committed to your root package, you must include the class loading information in the root package like that:

JavaScript:
{
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" }
  ],
  "name": "my-vendor/my-typo3-cms-distribution",
  "require": {
    "typo3/cms": "8.x-dev"
  },
  "autoload": {
    "psr-4": {
      "MyVendor\\MySitePackage\\": "typo3conf/ext/my_site_package/Classes"
    }
  }
}
Extension Manager
In Composer Mode functionality of the Extension Manager is limited. It will not be possible to download Extensions from TER, upload extension packages or update extensions. It will only be possible to list, activate and configure extensions.

Installing, updating, removing extensions and the TYPO3 core is exclusively allowed by using the composer commands.

Extension composer.json
Extension key / composer name
The composer name of an extension should have dashes "-" instead of underscores "_" (like the TYPO3 extension key). It is therefore required to add a replace section with the first value to contain the TYPO3 extension key.

JavaScript:
{
  "name": "vendor/my-extension-key",
  "type": "typo3-cms-extension",
  "version": "x.x.x",
  "description": "...",
  "require": {
    "typo3/cms-core": "^7.6.0"
  },
  "replace": {
      "my_extension_key": "self.version",
      "typo3-ter/my-extension-key": "self.version"
  },
  "autoload": {
    "psr-4": {
      "Vendor\\MyExtensionKey\\": "Classes/"
    }
  }
}
Classic Mode
Installation
Installation works exactly the same as know from previous TYPO3 versions. The only difference is, that if the TYPO3 sources are cloned from the git repository, a composer install --no-dev needs to be performed in the sources directory every time the sources are updated from the git repository. This ensures that all third party dependencies are loaded. This step is done before packaging the tarball releases, so no such action is required when using these.

Class Loading
The TYPO3 class loader has been removed in favor of the composer class loader, which also takes care of finding files for a given class name in Classic Mode. This has several implications for admins, integrators and developers:

ext_autoload.php files are NOT evaluated any more!
There is NO runtime evaluation of class files any more. This means a big performance boost and a more robustness during runtime.
Extension class loading information is only written and updated, every time an extension is activated or deactivated.
If no additional class loading information is found in extension meta data, the COMPLETE extension directory is scanned for class files. ALL found classes are then made available for class loading. This also means that adding classes during development, will only be found once the class loading information is updated.
PSR-4 compatible class loading information can be specified in a composer.json of the extension to ease development of extensions. It is recommended to do this in a composer.json file delivered by the extension. Alternatively this can be done similarly in the "autoload" section in the ext_emconf.php.
The class loading information of extensions will end up in typo3temp/autoload. Do NOT delete this directory, especially not in production environments. It contains vital information for your TYPO3 installation. If you need to update the class loading information, do it from command line php typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation
Composer cheatsheet for common scenarios
Composer warning after updating composer.json file
ANY change in composer.json, ​MUST​ also change the composer.lock file, as the composer.lock file incorporates a hash over the composer.json file content. You can perform composer update --lock if only minor things are changed (e.g. homepage or description). If dependencies are added or removed, please use composer update, composer remove package/name --update-with-dependencies for that, which will update the composer.lock automatically.

Be ready for production
Before deploying your code in production, don't forget to optimize the autoloader: composer dump-autoload --classmap-authoritative

This could also be used while installing packages with the --classmap-authoritative option. Without the optimization, you may notice a performance loss.


TYPO3 6.2.x
Warning - Message
This TYPO3 version comes with limited composer support. If you want to use composer for your TYPO3 installations, it is highly recommended to upgrade to TYPO3 7LTS
Basic TYPO3 Composer Distribution
TYPO3 can be required as package in any root composer.json (distribution). The composer package name of the complete TYPO3 sources is typo3/cms

The recommended base for your TYPO3 distribution is typo3/cms-base-distribution The "repositories" section in the composer.json of this distribution is required if you want to have access to all TER extensions as composer packages. See https://composer.typo3.org for details.

The "vendor-dir": "Packages/Libraries" configuration is required for advanced class loading capabilities.

Recommended minimum example composer.json:

JavaScript:
{
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" }
  ],
  "name": "my-vendor/my-typo3-cms-distribution",
  "config": {
    "vendor-dir": "Packages/Libraries",
    "bin-dir": "bin"
  },
  "require": {
    "typo3/cms": "6.2.x-dev"
  }
}
Doing a composer install will result in the following directory structure, which is not changeable for TYPO3 6.2.x!

-rw-r--r--   .gitignore
drwxr-xr-x   Packages
drwxr-xr-x   bin
-rw-r--r--   composer.json
-rw-r--r--   composer.lock
lrwxr-xr-x   index.php -> typo3_src/index.php
lrwxr-xr-x   typo3 -> typo3_src/typo3
drwxr-xr-x   typo3_src
IMPORTANT: This means the TYPO3 sources are downloaded or cloned into a typo3_src folder and index.php file and typo3 directory are set up as symlinks. This directory will then serve as document root directory of your installation.

Class Loading
To improve the reliability of TYPO3 6.2.x the composer class loader was added to TYPO3 6.2.10. Classes of all required TYPO3 extensions will be loaded by the composer class loader since that version.

Advanced Class Loading Setup
It is possible to require any third party composer package in your root composer.json, but TYPO3 normally will not make the classes of these packages available. However even since TYPO3 6.2.10 it is possible to have classes of all composer packages available if the TYPO3_COMPOSER_AUTOLOAD environment variable is set in your web server (or on the command line). If this is done, all classes of composer packages can be automatically loaded in your TYPO3 installation.

Besides that, you can specify class loading information for extensions and the core in your root composer.json, with the benefit of e.g. a more reliable deployment, since the old class loader will not be in charge any more.```

**Comment by sypets** [comment]
What I currently find missing in the docs is referring to the typo3/cms-composer-installers. Having a small "how it works" section and then referring there might suffice. (Anyone who wants to dig deeper can then look at the source). Not sure where this should be though.  Also, the information about the installer could be added to the docs in the installer (is currently just a readme).

---

This is what we currently have in the documentation:

Extension developers / developer perspective:

* composer.json for extensions: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html
* autoload: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Autoloading/Index.html

Install / Update

* migrate to Composer: https://docs.typo3.org/m/typo3/guide-installation/master/en-us/MigrateToComposer/Index.html
* Working with Composer (various tips and commands): https://docs.typo3.org/m/typo3/guide-installation/master/en-us/Composer/Index.html
* Install TYPO3 with Composer: https://docs.typo3.org/m/typo3/guide-installation/master/en-us/QuickInstall/Composer/Index.html
*

**Comment by susannemoog** [comment]
@sypets This is also still assigned to you. After reading through the content here, my suggestion would be to close this as long as the core developers do not pro-actively request this information for TYPO3 explained. For the "normal" TYPO3 user, the info is probably too much. Those that really want to dig into the internal composer handling of TYPO3 will find the type installer quickly enough and read the readme there and the code.

**Comment by linawolf** [comment]
Lets close this, feel free to provide a PR
