### ISSUE TITLE
Hint for abandoned core extensions

### ISSUE THREAD

**Issue by mhuber84** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#173]
Sometimes core extension get removed or merged into other extension. If you want to know why this happened, you have to search in the breaking changes for the extension key (not package name!). A litte hint on [this site](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/Upgrade/InstallTheNewSource/Index.html) for this would be very helpful.

The same hint would be helpful on get.typo3.org: https://github.com/TYPO3/get.typo3.org/issues/197

**Comment by susannemoog** [comment]
Patch was merged, thanks!
