### ISSUE TITLE
Declaration not compatible: canConvertFrom($source, $targetType) in 'Form' 'Extbase' 'form_legacy'

### ISSUE THREAD

**Issue by cwvb** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#191]
Typ3 CMS Bootstrap 10.4.12 PHP Version 7.3.23  (unter Version: 9.5.24 läuft die Seite ohne diese Fehler)
1. im Backend erzeugt der Aufruf einzelner Funktionen weiße Seiten: z. B. (jeweils im 'Modulmenü') 'Erweiterungen-Erweiterungen hinzufügen' und in 'Indizierung' und in 'Slugs'
Mit eingeschaltetem Debugger kommen immer Meldungen im Zusammenhang mit TypeConverter Validation und einer nicht übereinstimmenden Declaration in diesen drei Erweitungen: 'Form' 'Extbase' 'form_legacy'. So sehen die Meldungen aus: 
"Fatal error: Declaration of TYPO3\CMS\Form\Domain\Property\TypeConverter\ArrayToValidationElementConverter::canConvertFrom($source, $targetType) must be compatible with TYPO3\CMS\Extbase\Property\TypeConverter\AbstractTypeConverter::canConvertFrom($source, string $targetType): bool in /PROVIDER/KUNDE_ACCOUNT/WWW/Typo3_V10412/typo3conf/ext/form_legacy/Classes/Domain/Property/TypeConverter/ArrayToValidationElementConverter.php on line 124"

Da ähnliche Meldungen von mehreren Aufrufen ausgelöst werden, weiß ich nicht genau wo (überall) ein vielleicht einfacher Eingriff möglicherweise erfolgreich wäre.
Z. B. (NUR ) hier:
typo3conf/ext/form_legacy/Classes/Domain/Property/TypeConverter/ArrayToValidationElementConverter.php
UND (ODER oder NUR nicht) hier:
CMS\Form\Domain\Property\TypeConverter\ArrayToValidationElementConverter::canConvertFrom($source, $targetType)

Ist also die Systemerweiterungen 'Form' der Übeltäter oder die Erweiterung 'form_legacy'?
Abschalten kann ich sie übrigens nicht über den Extensionmanager, da dieser Aufruf den Fehler auch auslöst.
Ich bin natürlich zu allen Übeltaten bereit, wenn ich klarer sähe.
Vielleicht muss/sollte ja auch der Autor der Extension (s) da was schrauben....
Die Extension 'form_legacy' ist seit 2017 nicht mehr verändert worden, (und wird als kompatibel mit 8 LTS angegeben). 
Muss ich Ihre Funktion ersetzen mit Version 10 eigenen Mitteln?
Bisher konnte ich die Seite immer 'mitnehmen' und anpassen an die jeweiligen LTS.

Mit freundlichen Grüßen
CWvB

**Comment by mbrodala** [comment]
Please [join us in Slack](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Account/Slack.html) to ask support questions. Make sure you use English for a broader audience. ;-)
