### ISSUE TITLE
Install with SELinux on

### ISSUE THREAD

**Issue by xyzelt** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#192]
Maybe is good to add SELinux at requirements or troubleshooting.
I have a fresh minimal CentOS 7 , install all requirements for typo3 without composer, create public folder with correct rights for apache, but installer can't create folders.
Without setools installed i don't know what is wrong.
I have changed default context type from httpd_sys_content_t to httpd_sys_rw_content_t:
chcon -R -t httpd_sys_rw_content_t /xxx/public , and for persistence: semanage fcontext -a -t httpd_sys_rw_content_t /xxx/public

Next problem was when i try to connect and create database, fix was: setsebool httpd_can_network_connect 1

**Comment by linawolf** [comment]
The topic of installation was moved to the Getting Started Guide. And unfortunately we cannot mention every setup thinkable. We need to stick to the most common examples.
