### ISSUE TITLE
Avoid unquoted wildcard Composer commands

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#275]
Composer commands like `composer update typo3/*` can lead to issues if the shell tries to expand the wildcard `*`. Even worse if there are actually matching files for the given "path".

Thus commands like these should always quote the package name like `"typo3/*"` to avoid shell expansion.

**Comment by DavidBruchmann** [comment]
So I think this can be closed.  
@mbrodala feel free to re-open or to ask for it if my impression is wrong.
