### ISSUE TITLE
No link in "see subtree split for details"

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#287]
https://docs.typo3.org/m/typo3/guide-installation/main/en-us/MigrateToComposer/MigrationSteps.html#install-the-core says:
> Since version 9 TYPO3 must be installed using individual typo3/cms-* packages (see “subtree split” for details). 

"subtree split" is not linked, nor is there anything to find when searching for "subtree split" on this page.

Please add a link to the relevant documentation.

**Comment by mbrodala** [comment]
Not sure if we should link to https://usetypo3.com/typo3-subtree-split-and-composer.html or https://typo3.org/article/typo3-release-improvements-v8-maintenance-release-schedule/#c7095 here ...
