### ISSUE TITLE
Add note about cms-composer-installers v4 to Minor Upgrade Guide

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#293]
As discussed with @bnf @helhum @nhovratov @krausandre in our meeting about the composer installer we'd like to have a notice about the changed directory layout with `typo3/cms-composer-installers` version 4 here:

https://docs.typo3.org/m/typo3/guide-installation/main/en-us/Minor/Index.html

It could link to some more information and recommend to `composer require typo3/cms-composer-installers:^3` to opt-out of that change.

**Comment by linawolf** [comment]
@jonaseberle you have some detailed information for me here?

**Comment by DavidBruchmann** [comment]
@linawolf these are some details and as far as I see they are already covered in the documentation:

- new folder `public/_assets` with symlinks to the folder `Resources/Public` in each extension, this includes system-extensions.
- extensions including system-extensions are installed in the folder vendor.
- the files LocalConfiguration.php and AdditionalConfiguration.php are no longer resided in typo3conf, but renamed and stored in config/system as settings.php and additional.php.
- all extensions require a file composer.json.
- extension internal links to translation files, templates, assets, etc. have either to follow extbase logic or use the syntax 'EXT:extension'. Old links that include instead 'typo3conf/ext/' in the path are usually not recognized or mapped to the new location in vendor, so they are not working anymore.

These are the most important changes, might be that I forgot to mention something.

**Comment by garvinhicking** [comment]
This has been adressed now with this PR https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/379 as well as a ChangeLog entry of TYPO3v12.
