### ISSUE TITLE
Make running commands for upgrade tasks via cli the default (not via GUI)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#294]
On the page https://docs.typo3.org/m/typo3/guide-installation/main/en-us/Major/PostupgradeTasks/Index.html, for several commands only the GUI version is shown and either the commands as alternatives or the commands are not listed at all.

I propose to show the commands as preferred version and ideally in all in one place so you don't have to scroll through several screenshots.

* upgrade wizards
* run database analyzer: no command line variant shown
* clear user settings: no command line variant shown. Also, the description is a bit vague:

> You might consider clearing the Backend user preferences. This can avoid problems, if something in the upgrade requires this. 

* clear cache: no command line variant shown
* update backend translations: no command line variant shown
* clear processed files: no command line version shown

**Comment by linawolf** [comment]
The Upgrade guide was moved into TYPO3 Explained. Please reopen your issue there if it is still of relevance.
