### ISSUE TITLE
Define composer patches in  separate .json file (not in composer.json)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#306]
_low priority, not a bug, but a general best practice thing._

I would put the definition for the composer patches in a separate json file. For the following reasons:

* it declutters the composer.json
* This makes it more flexible. Every time composer.json is changed a hash is generated and the composer.lock must be updated too.

(In the documentation, the patches are listed in the `composer.json` file.)

See also [core 11.5](https://github.com/typo3/typo3/tree/11.5) where it is done this way:

composer.json

```
"extra": {
                ...
                "composer-exit-on-patch-failure": "true",
                "patches-file": "Build/patches/patches.json"
        },
```

Build/patches/patches.json:

```
{
	"patches": {
		"doctrine/dbal": {
			"[BUGFIX] Avoid deprecated variable interpolation with PHP8.2": "Build/patches/postgres-platform-variable-interpolation-php82-fix.diff"
		}
	}
}

```

https://docs.typo3.org/m/typo3/guide-installation/main/en-us/ApplyingCorePatches/Index.html#automatic-patch-application-with-cweagans-composer-patches

**Comment by linawolf** [comment]
The Upgrade guide was moved into TYPO3 Explained. Please reopen your issue there if it is still of relevance.
