### ISSUE TITLE
Minor update instructions: Add "-m" option to "composer outdated ..."

### ISSUE THREAD

**Issue by knbknb** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#307]
On this page [What are minor updates](https://docs.typo3.org/m/typo3/guide-installation/main/en-us/Minor/Index.html#what-are-minor-upgrades)
it explicitly says 

> "For example, upgrading from TYPO3 version 11.5.2 to 11.5.3 is a minor upgrade."

And the instructions say in Paragraph [Check if updates are available](https://docs.typo3.org/m/typo3/guide-installation/main/en-us/Minor/Index.html#check-if-updates-are-available) 

> Alternatively, running `composer outdated "typo3/*"` will present a list of any packages that have updates.

But this command is incorrect, it should be 

> Alternatively, running `composer outdated -m "typo3/*"` will present a list of any packages that have minor version updates. 

`composer outdated --minor-only "typo3/*"` could also be used.

Otherwise (without `-m`) the listing will display *major* version updates
`typo3/cms-indexed-search       v10.4.31 v12.1.3`  
only with `-m` switch it will show the actual minor version updates
`typo3/cms-indexed-search       v10.4.31 v10.4.34`

**Comment by DavidBruchmann** [comment]
@knbknb thanks for reporting  this issue!  
Both commands display almost the same information, it's slightly different though, below the essential parts of the output:

**composer outdated "typo3/*"**  

![image](https://user-images.githubusercontent.com/999146/221101938-c81c3cb4-8c6b-4179-beaa-a38764d7b611.png)

**composer outdated -m "typo3/*"**  

![image](https://user-images.githubusercontent.com/999146/221102074-1417454e-dcfa-40a4-9513-5a424b3bf88c.png)

I might be reasonable to change the documentation, I'm not 100% sure about it.  
@linawolf , @brotkrueml what's your opinion?

**Comment by knbknb** [comment]
They display vastly different output on my machine, which is contains a 10.4.

 Without `-m` a lot of 12.x  updates are displayed, almost as if TYPO3 urges me to upgrade. Only with `-m` I can see most recent minor version 10.4 updates. 
I don't know why this is, maybe its my global composer configuration, if there is such a thing (a `$COMPOSER_HOME/.config` does not exist on my machine).
I have also noticed this behavior with outher PHP projects, not just TYPO3. `-m` works better. 

Maybe it's dependent on the composer version. Ubuntu 18.04 and 20.04 still have composer 1 in their distro repositories, and you'll get composer2 only if you install via the composer.phar file mechanism.

Do what you want, I don't care (= **I  don't want to reopen this**), personally I will prefer to use the `-m` composer option.

**Comment by DavidBruchmann** [comment]
You're right, you can see my screenshots above too, they confirm your words.  
Your proposed change is in the documentation and should be online already visible.
Thanks for reporting, I think it's very useful!
