### ISSUE TITLE
Streamline description of post-deployment and post upgrade tasks

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#341]
I am creating issue here. I would like to address 2 other things first. Also, this is a bit difficult to solve, so it might make sense to write this up elsewhere and then decide how to integrate it into existing documentation in second step.

### Current behavior

* the [section on extension updates](https://docs.typo3.org/m/typo3/guide-installation/main/en-us/UpgradingExtensions/Index.html) has no post update tasks (e.g. extension:setup, cache:flush, download languages...)
* some of the [post upgrade tasks](https://docs.typo3.org/m/typo3/guide-installation/main/en-us/UpgradingExtensions/Index.html) in the section "major updates" apply not just for major updates of the core (so a general page or section for post deploy tasks might make sense)
* the [post upgrade tasks](https://docs.typo3.org/m/typo3/guide-installation/main/en-us/UpgradingExtensions/Index.html) section focuses on GUI. There are no cli variants listed for clearing the caches, updating languages etc. (I think the main thing should be the cli commands, ideally on top of the page)

### Expected behavior/output

either 

* have a general page for post deployment tasks (not just for major updates), regardless of what changed. Explain which tasks are needed when (e.g. breaking changes in general: core or extension, ) and what each task does
* or add the post deployment task in each section where thy apply (I think this is not ideal. There is bound to be a lot of overlap).

For the command line versions of the tasks. Ideally:

* have all the command line actions in one place with short explanation for each (cache:flush, download languages,

### Links

* extension updates: https://docs.typo3.org/m/typo3/guide-installation/main/en-us/UpgradingExtensions/Index.html
* post upgrade tasks: https://docs.typo3.org/m/typo3/guide-installation/main/en-us/UpgradingExtensions/Index.html

### TYPO3 versions

main, ...

## Important / Danger

Unfortunately, deployment and post deployment is a bit tricky and it might make sense to optimize the order for minimal downtime (e.g. do not flush entire cache at once, flush the di and system cache and warm it up, flush the page cache after).

Also unfortunately, it is difficult to give general recommendations as some of this may depend on the system setup. But we can maybe give some basic guidance.

## Additional context

(needs to be checked for each TYPO3 version, I base my information on TYPO3 v11 for now). 

The order also should be checked, but is mostly correct.

**This is for major updates, not all tasks are necessary for every deployment!**

Rough draft:

(optional):  **before** updating, lock BE 

`php vendor/bin/typo3 backend:lock`

After updating:

_1. Basic setup:_

`php vendor/bin/typo3 extension:setup`

_2. Update DB schema:_ (this is typo3_console, and it may be redundant if extension:setup is called):

`php vendor/bin/typo3cms database:updateschema`

_3. Upgrade wizards_ (is already mentioned on "post upgrade tasks)

`php vendor/bin/typo3 upgrade:run`

_4. Flush and warmup system cache, di cache and opcache_ (as mentioned above, probably separate cache flushing this to flush and warmup system and di cache first and page cache later, after removing the processed files)

!!! also opcache should be flushed here

```
php vendor/bin/typo3 cache:flush -g di
php vendor/bin/typo3 cache:warmup -g di
php vendor/bin/typo3 cache:flush -g system
php vendor/bin/typo3 cache:warmup -g system
# flush opcache, e.g. service reload php-fpm or use gordaline/cachetool or ...
```

_4. Flush processed files_ (page cache should be flushed afterwards, but good idea to do this after flushing and warming up system cache and di)

... no cli core functionality available?

_5. Update translations:_

`php vendor/bin/typo3 language:update`

_6. Remove user settings_ (optional)

 no cli command for this

_7.  unlock BE_ (can already unlock BE here (so will only be locked as long as necessary, ideal would be after flushing processed file because of thumbnails in BE, and possibly after flushing page cache to reduce load and side effects from BE user actions)

`php vendor/bin/typo3 backend:unlock`

_8. flush page cache_

`php vendor/bin/typo3 cache:flush -g pages`

_9. warmup page cache_

No core functionality to warmup all pages, but should be mentioned, can use this as minimal:

`php vendor/bin/typo3 cache:warmup -g pages`

**Comment by linawolf** [comment]
The Upgrade guide was moved into TYPO3 Explained. Please reopen your issue there if it is still of relevance.
