### ISSUE TITLE
Video not loading on install instruction website

### ISSUE THREAD

**Issue by baurma** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#350]
### Current behavior

When I open the documentation how to install typo3 in a web browser, i.e. open the website https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/Composer/Index.html
the video at the bottom is not shown because it is "private"

### Expected behavior/output

I expect the video to render properly in any current web browser.

### Links

https://youtu.be/M4imQOUKDe4

### TYPO3 versions

any

### Possible Solution

Fix video permissions or reupload video

### Additional context

none

**Comment by brotkrueml** [comment]
@baurma Thanks for the hint. I removed the video from the page.
