### ISSUE TITLE
Upgrade guide to 12.4 - might be for another version

### ISSUE THREAD

**Issue by florinphp** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#353]
The documentation for upgrade to 12.4 from 11.5, is actually the old documentation to 11 from 10.

https://docs.typo3.org/m/typo3/guide-installation/12.4/en-us/Major/UpgradeCore.html

> ... running TYPO3 version 10.4.22 and the new LTS release is version 11.5.0.

**Comment by garvinhicking** [comment]
Thanks for reporting! This has meanwhile been fixed :-)
