### ISSUE TITLE
explain 'composer update --with-all-dependencies "typo3/*"' more thoroughly

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#388]
```suggestion
This will update all TYPO3 packages, the :bash:`--with-all-dependencies` signals that any dependencies of TYPO3 should also be updated with respect to the version constraints given by the TYPO3 packages.
```

_Originally posted by @DavidBruchmann in https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/387#discussion_r1621779788_

**Comment by franzholz** [comment]
Please wait for the other PR first!

https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/387

**Comment by linawolf** [comment]
The Upgrade guide was moved into TYPO3 Explained. Please reopen your issue there if it is still of relevance.
