### ISSUE TITLE
Please bring back version specific information for major upgrades

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#390]
### Current behavior

For upgrading to v12, there are a few "gotchas" which are currently not documented in the upgrade guide (typo3/cms-recordlist no longer available, changes in file structure and typo3/cms-composer-installers, typo3cms (typo3_console) no longer exists.

### Expected behavior/output

Find concise information for upgrades specific to a version without having to read entire Changelog first. 

### Links

* v12: Major Upgrades: https://docs.typo3.org/m/typo3/guide-installation/12.4/en-us/Major/Index.html

### TYPO3 versions

* **12** (would also concern 11, but not aware of anything special necessary for 11), also possibly 13

### Possible Solution

We used to have a page in the Upgrade Guide (or Installation Guide as it was called previously) for information for specific versions, in addition to the general information. 

I remember migrating some of those from the wiki, they are still there for older versions, e.g.

* [10.4](https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/Upgrade/UpgradeToLts/Index.html)
* [9.5](https://docs.typo3.org/m/typo3/guide-installation/9.5/en-us/Upgrade/UpgradeToLts/Index.html)
* [8.7](https://docs.typo3.org/m/typo3/guide-installation/8.7/en-us/Upgrade/UpgradeToLts/Index.html) 

Since 11.5, this is missing.

### Additional context

I think having the separate page is the best possible solution, because adding the version specific information to the general information would make it difficult for people who have already performed multiple updates and don't need / want to read the entire instructions.

**Comment by sypets** [comment]
For TYPO3 v12, this is what I found so far (I am only considering the **actual upgrade process**, not the necessary changes in extensions. that part is mentioned in the docs to check out changelog, extension scanner etc. and would probably be too extensive).

* typo3/cms-recordlist removed: [Breaking: 98443 - Extension recordlist merged into backend](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98443-ExtensionRecordlistMergedIntoBackend.html)
* ["Important: 98484 - Extensions and assets outside of document root for Composer-based TYPO3 installations"](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Important-98484-ExtensionsOutsideOfDocumentRootForComposer-basedTYPO3Installations.html)
* [typo3_console no longer has binary typo3cms](https://github.com/TYPO3-Console/TYPO3-Console). This is not specific to core, but installations used to rely heavily on typo3_console and might deserve a mention:

> Important information for longtime users
> The CLI binary typo3cms was removed with version 8.0.0 and is replaced by the TYPO3 CLI binary typo3. Commands that were called e.g. typo3cms database:updateschema before, must now be called with typo3 database:updateschema.

* there is also a section for ckeditor in Sebastian Klein's blog, and a changelog: [Feature: 96874 - CKEditor 5](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96874-CKEditor5.html)

Additional information for upgrade to v12:

* (in German) Sebastian Klein: https://www.sebkln.de/news/upgrade-typo3-v12/
* (in English) Chris Müller: [Migration to typo3/cms-composer-installers version 4+](https://brotkrueml.dev/migration-typo3-composer-cms-installers-version-4/)

**Comment by DavidBruchmann** [comment]
The changed folder structure is explained here: https://docs.typo3.org/m/typo3/guide-installation/12.4/en-us/Major/PreupgradeTasks/Index.html#convert_global_extensions

**Comment by fe-hicking** [comment]
I think I remember discussing this with @brotkrueml at the codesprint. I think we were under the impression that the ChangeLogs are the source of information on all breaking changes and that these would need to be read. Highlighting only a bit of that for an upgrade might be misleading people into thinking that would be all to cover. We wanted to encourage reading the breaking changes ans important changelogs. Please correct me if I remember this wrong, Chris.

Also, it is a huge task to comb through all changelogs and create a "best of".

Having said that, if a good and complete list for this is contributed, I think we could include it?!

**Comment by brotkrueml** [comment]
Garvin and me also discussed to revive the "What's new slides" (in one way or another) - but that is a lot of work which has to be done somehow by someone.

I agree with Garvin, that we can only scratch the surface with documenting changes in the Upgrade Guide - mostly a list of topic and linking them to the changelog. But this wouldn't be as comprehensive and detailled as "scrolling" through the changelog. A developer has to go through the changelog (mostly the breakings and deprecations) on upgrade and look if a topic is relevant for them.

The changelog is already mentioned:
https://docs.typo3.org/m/typo3/guide-installation/12.4/en-us/Major/PreupgradeTasks/Index.html#check-the-changelog-and-news-md

But, if someone wants to volunteer for that task: Go ahead.

**Comment by sypets** [comment]
I don't mean to document the entire changes - just what is specifically different for the version when performing the upgrade steps - such  as already outline above. 

However, I realize the decision what would be documented on the page and what not might be a little fuzzy.

Also, you are right, we do have the changelogs. And I found the blog entries with the summaries.

So closing now. Thanks for your thoughts.
