### ISSUE TITLE
Autoload without composer in which file?

### ISSUE THREAD

**Issue by bambino-aholics** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#47]
https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/Autoloading/Index.html#loading-classes-without-composer-mode

I miss the file, where I have to include the code snippet for autoloading without composer.

**Comment by sypets** [comment]
@bambino-aholics Oh, you mean this snippet?

```
<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath();

return array(
   'Schnitzler\\Templavoila\\Clipboard\\Clipboard' => $typo3InstallDir . 'typo3conf/ext/templavoila/Classes/Clipboard/Clipboard.php',
   'tx_templavoila_pi1' => $typo3InstallDir . 'typo3conf/ext/templavoila/Compatibility/class.tx_templavoila_pi1.php',
   ...
);
```

Well, as far as I understand, that is not a code snippet you include, that is the sample content of the automatically generated autoload_classmap.php, for example look in typo3conf/autoload/autoload_classmap.php on a TYPO3 8 non-composer installation (was in typo3temp/autoload in older installations).

But I'll try to add some more clarification in that section and will try to get someone to check, if this is still up to date. 

In any case, using composer is recommended, under TYPO3  you can also initiate the autoloading from the install tool or in TYPO3 9 from the backend. Usually, you don't have to worry about autoloading. It should work automatically.

In any case, if you have further questions, please ask in Slack #typo3-cms or on StackOverflow (with tag typo3), see https://typo3.org/help

**Comment by sypets** [comment]
No feedback and probably outdated. Also, information about autoloading is in "TYPO3 Explained". I am closing.
