### ISSUE TITLE
Where create documentation in another language, not English?

### ISSUE THREAD

**Issue by typo3ua** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#49]
If i want create documentation in another language, not English, where can I do it?

For example: "TYPO3 Installation and Upgrade Guide in Ukrainian language"

**Comment by sypets** [comment]
This has not been documented yet and there has been some restructuring in the rendering, so currently, translations of official manuals are not rendered.

**Before you put in lots of work to get started, please consider**: Are you willing to maintain this long term? Do you have at least one or two other people who are willing to do this with you? This means, every time a new TYPO3 version comes out, you may have to update the manual. 

The documentation Team only maintains English manuals and it cannot even check if manuals are outdated, if it does not master the foreign language. 

You might also consider, [asking in Slack](https://docs.typo3.org/typo3cms/HowToDocument/HowToGetHelp.html). You can get a final, more authoritative answer from Martin Bless. 

That being said, multilingual support is great in TYPO3 and there is much advantage in having the basic manuals in several foreign languages. 

To get started:

1. I would strongly advise that you use a local workflow (e.g. see [Local Editting and Rendering with Docker](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/LocalEditing.html))
2. You create the translated version by starting another manual under the path `Documentation/Localization/uk-UA`. Copy the complete English manual (everything under `Documentation`) to this folder. When you are done, there should be a file Settings.cfg under `Documentation/Localization/uk-UA/`
3. Work by translating the files. You can keep the structure (and filenames) from the English manual. Translate everything else. That has the advantage that later, everyone can switch between languages on any page. 
4. When you are done, submit your pull request (see link in 1.)

Happy editing!

For an example, of a rendered translated extension manual, see [ext:sphinx](https://docs.typo3.org/typo3cms/extensions/sphinx/). Click on "Related Links". The branches with "fr" are the translated French version.

**Comment by typo3ua** [comment]
I will try do it... Thanks!
