### ISSUE TITLE
Add clarification and explanation for base-distribution

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#55]
see also https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/issues/10

**Comment by helhum** [comment]
See: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/19#issuecomment-530409648

**Comment by susannemoog** [comment]
I'm trying to figure out if there is still anything to do here, as the guide now contains commands that work both on windows and linux and even explicitly state the ddev variant - see https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/Composer/Index.html
Imho this could be closed //cc @sypets ?

**Comment by sypets** [comment]
Yes. closing.
