### ISSUE TITLE
Add information about how to run upgrade wizards from command line for non Composer installations

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#76]
https://docs.typo3.org/typo3cms/InstallationGuide/Upgrade/UseTheUpgradeWizard/Index.html

See also [Question on StackOverflow](https://stackoverflow.com/questions/56109788/how-to-run-upgrade-wizards-from-command-line-in-typo3-8)

**Comment by sypets** [comment]
Is done.

**Comment by jokumer** [comment]
There is a mistake in path. Instead of
`.typo3/sysext/core/bin/typo3`
it should be
`./typo3/sysext/core/bin/typo3`

I wil fix this together with the versions for v9.5, 8.7 and 7.6 in issue #90
