### ISSUE TITLE
Correct information about TYPO3 versions in "Handling Deprecations"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#77]
see https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/74#discussion_r283483904

Daniel Siepmann:

> "Minor versions are always backwards compatible" is not true. TYPO3 does not use semantic versioning. Even security patches and bug fixes might introduce breaking changes.

https://docs.typo3.org/typo3cms/InstallationGuide/Upgrade/Preparation/Index.html#handling-deprecations

* [ ] Also, where should information about TYPO3 versions be? Is it already documented somewhere?

## Related: 

* #74

**Comment by susannemoog** [comment]
Added a PR for the text change, as for info about TYPO3 versions, I think we should leave most version specific information on get.typo3.org.
